# yaml-language-server: $schema=https://raw.githubusercontent.com/luisnquin/senv/main/docs/senv.schema.json

env_file: ./.env
envs:
  - name: dev
    variables:
      HOST: localhost
defaults:
  PORT: 8080
