on:
  release:
    types:
      - released

env:
  committer_name: Lucy Diniz
  committer_email: lucydiniz.rs@gmail.com

jobs:
  update:
    name: Update default.nix
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Update version and commit
        run: |
          LATEST_COMMIT=$(git rev-parse HEAD)
          LATEST_TAG=$(git describe --tags --abbrev=0)

          sed -i "s/commit = \".*\";/commit = \"$LATEST_COMMIT\";/g" default.nix
          sed -i "s/version = \".*\";/version = \"$LATEST_TAG\";/g" default.nix
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: default-nix-update

          delete-branch: true
          token: "${{ secrets.PULL_REQUEST_BOT_TOKEN }}"
          title: "Updated default.nix version and commit"
          commit-message: "chore(nix): updated version and commit"
          committer: ${{env.committer_name}} <${{env.committer_email}}>
          base: main
          body: |
            Automated changes by **nix-update** Action.
