name: go
on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache-dependency-path: ./go.sum
          go-version-file: ./go.mod
          go-version: ">=1.18.0"
          check-latest: false
      - name: Build
        run: go build -v ./...

  formatting:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Gofumpt
        uses: luisnquin/setup-gofumpt@v1.0.0

      - name: Check *.go files format
        run: |
          [ "$(gofumpt -d ./..)" = "" ]
