name: go

on: [push, pull_request]

jobs:
  build-test:
    name: Build test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Painful
          fetch-tags: true
      - name: Install Just
        uses: extractions/setup-just@v1
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          cache-dependency-path: ./go.sum
          go-version-file: ./go.mod
          go-version: ">=1.18.0"
          check-latest: false
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = flakes nix-command
      - name: Build test
        run: just build-test

  test:
    name: Test Go files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Painful
          fetch-tags: true
      - name: Install Just
        uses: extractions/setup-just@v1
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          cache-dependency-path: ./go.sum
          go-version-file: ./go.mod
          go-version: ">=1.18.0"
          check-latest: false
      - name: Test Go files
        run: just test

  format-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Gofumpt
        uses: luisnquin/setup-gofumpt@v1.0.0
      - name: Check .go files format
        run: |
          [ "$(gofumpt -d ./..)" = "" ]
